version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firstdb
    ports:
      - "5432:5432"
    networks:
      - app-network

  springboot-app:
    build: .
    container_name: springboot-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/firstdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
